apiVersion: v2
name: customer-center
description: Chart for Customer-Center frontend
type: application
version: "0.0.0"
appVersion: "latest"
keywords:
  - customer-center
home: https://github.com/adfinis/customer-center
sources:
  - https://github.com/adfinis/customer-center
  - https://github.com/adfinis/helm-charts/tree/main/charts/customer-center
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "fix: remove duplicate managed-by label"
