---
name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build the prod image
        working-directory: ./backend
        run: |
          docker build .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Lint the code
        run: |
          echo "UID=$UID" > .env
          docker compose run --rm backend ruff format --check
          docker compose run --rm backend ruff check . --output-format=github

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set ENV vars
        run: echo "UID=$UID" > .env
      - name: Check for missing migrations
        run: docker compose run --rm backend python manage.py makemigrations --check --dry-run --no-input
      - name: Run pytest
        run: docker compose run --rm backend pytest --no-cov-on-fail --cov --create-db -vv
