---
name: Charts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/
          load: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/
          load: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest

      - name: Build customer-center image
        uses: docker/build-push-action@v6
        with:
          context: ./customer-center/
          load: true
          tags: ghcr.io/${{ github.repository }}/customer-center:latest

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Load dev images into k8s
        run: kind load docker-image ghcr.io/${{ github.repository }}/backend ghcr.io/${{ github.repository }}/frontend ghcr.io/${{ github.repository }}/customer-center --name chart-testing

      - name: Load bitnami image into k8s
        run: |
          docker pull --platform linux/amd64 bitnamilegacy/postgresql:17.6.0-debian-12-r4
          docker tag bitnamilegacy/postgresql:17.6.0-debian-12-r4 bitnami/postgresql:17.6.0-debian-12-r4
          docker save bitnami/postgresql:17.6.0-debian-12-r4 | kind load image-archive /dev/stdin --name chart-testing

      - name: Install kube-prometheus stack CRDs
        run: |
          export KUBE_PROMETHEUS_STACK_VERSION=58.4.0
          kubectl apply -f https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-$KUBE_PROMETHEUS_STACK_VERSION/charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
          kubectl apply -f https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-$KUBE_PROMETHEUS_STACK_VERSION/charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
          kubectl apply -f https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-$KUBE_PROMETHEUS_STACK_VERSION/charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml

      - name: Run chart-testing (install)
        run: ct --config=ct.yaml install
