---
name: ui-core CI

on:
  push:
    branches: [main]
    paths: ["ember/ui-core/**"]
  pull_request:
    paths: ["ember/ui-core/**"]

env:
  NODE_VERSION: 20

defaults:
  run:
    working-directory: ./ember/ui-core

jobs:
  lint:
    runs-on: [ubuntu-latest]
    timeout-minutes: 5

    strategy:
      matrix:
        target: [js, hbs, format, types]

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          package_json_file: "ember/package.json"

      - run: |
          mkdir -p ~/.local/share/pnpm/store/v10
          pnpm config set store-dir ~/.local/share/pnpm/store/v10

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: ember/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint ${{ matrix.target }}
        run: pnpm lint:${{ matrix.target }}

  test:
    needs: [lint]
    runs-on: [ubuntu-latest]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          package_json_file: "ember/package.json"

      - run: |
          mkdir -p ~/.local/share/pnpm/store/v10
          pnpm config set store-dir ~/.local/share/pnpm/store/v10

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: ember/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
